---
- name: test
  hosts: nodes
  become: yes
  serial: 1
  tasks:
    - name: Check the uptime prior reboot
      shell: uptime
      register: UPTIME_PRE_REBOOT
      throttle: 1

    - debug: msg={{UPTIME_PRE_REBOOT.stdout}}

    - name: Reboot system
      reboot:
        reboot_timeout: 1200
        test_command: mount

    - name: wait for host to finish reb00t
      wait_for:
        port: "{{ (ansible_port|default(ansible_ssh_port))|default(22) }}"
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH

    - name: Check the uptime post reboot
      shell: uptime
      register: UPTIME_POST_REBOOT

    - debug: msg={{UPTIME_POST_REBOOT.stdout}}
